print("hello world")
print("what is your name")
myname=input()
print("it's good to meet u " + myname)
print("the length of your name is:")
print(len(myname))
print("what is your age")
myage=input()
print("you will be"+str(int(myage)+1)+"in a year")
